### ISSUE TITLE
Unofficial HockeySDK nuget package has debug binaries

### ISSUE THREAD

**Issue by jgcoded** [mathieumack/HockeySDK-Windows#2]
When I create a UWP package created by using the Desktop Bridge on a WPF app, and run it through the Windows App Cert Kit, I fail two tests because of the HockeyApp dlls:

![image](https://user-images.githubusercontent.com/4654930/36647787-855fcd6e-1a3f-11e8-8dec-3043346e7541.png)

**Comment by mathieumack** [comment]
Hi,
The dll is builded in Release mode, not in Debug.
Perhaps that an other flag or constant on the dll is reconized from the certification toolkit.
Could you download the sources, build on Release mode and try to reference from your project the builded dll to check if you reproduce the problem ?
Best regards

**Comment by jgcoded** [comment]
Hey sorry to get back to you so late - I'm not using the HockeySDK anymore, so I can't repro this anymore

**Comment by mathieumack** [comment]
Ok, it's a good news if your problem is solved.
